version: '3.8'

services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: misa_server
    restart: unless-stopped
    ports:
      - "5001:8001"
    env_file:
      - ./server/.env
    depends_on:
      - misa-redis
    networks:
      - misa_net
  client:
    container_name: misa_client
    build:
      dockerfile: Dockerfile
      context: ./client/
    env_file:
      - ./client/.env
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - misa_net
  smtp-service-misa:
    image: maildev/maildev
    container_name: smtp-service-misa
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--no-warnings=DeprecationWarning
      - DEBUG=maildev*
    env_file:
      - ./server/.env
    command:
      --outgoing-host smtp.gmail.com
      --outgoing-port 465
      --outgoing-secure
      --outgoing-user mailer7012@gmail.com
      --outgoing-pass "ldxm ypzz ewvf mnwq"
      --auto-relay
      --verbose
    ports:
      - "8191:1080"
      - "1025:1025"
    networks:
      - misa_net
  misa-redis:
    image: redis:7-alpine
    container_name: misa-redis
    restart: unless-stopped
    ports:
      - "6384:6379"
    networks:
      - misa_net

networks:
  misa_net:
    driver: bridge
