import { LANGUAGES } from "./locale.js";

/** OG / meta description: «Misa Chat — …» for each locale from LANGUAGES (unlisted → English). */
const EN = "Misa Chat — modern messenger";

const TAGLINES = {
    en: EN,
    ru: "Misa Chat — современный мессенджер",
    de: "Misa Chat — moderner Messenger",
    ar: "Misa Chat — مراسل عصري",
    sq: "Misa Chat — mesazhier modern",
    am: "Misa Chat — ዘመናዊ መልዕክተኛ",
    hy: "Misa Chat — ժամանակակից մեսենջեր",
    az: "Misa Chat — müasir mesencer",
    eu: "Misa Chat — messenger modernoa",
    be: "Misa Chat — сучасны месенджар",
    bn: "Misa Chat — আধুনিক মেসেঞ্জার",
    bg: "Misa Chat — модерен месинджър",
    my: "Misa Chat — ခေတ်မီမက်ဆေ့ခ်ျ",
    ca: "Misa Chat — missatger modern",
    zh: "Misa Chat — 现代即时通讯",
    "zh-TW": "Misa Chat — 現代即時通訊",
    hr: "Misa Chat — moderan glasnik",
    cs: "Misa Chat — moderní messenger",
    da: "Misa Chat — moderne messenger",
    nl: "Misa Chat — moderne messenger",
    et: "Misa Chat — kaasaegne messenger",
    fi: "Misa Chat — moderni messenger",
    fr: "Misa Chat — messager moderne",
    gl: "Misa Chat — mensaxeiro moderno",
    ka: "Misa Chat — თანამედროვე მესენჯერი",
    el: "Misa Chat — σύγχρονος αγγελιοφόρος",
    he: "Misa Chat — שליח מודרני",
    hi: "Misa Chat — आधुनिक मैसेंजर",
    hu: "Misa Chat — modern üzenetküldő",
    is: "Misa Chat — nútímalegur sendill",
    id: "Misa Chat — messenger modern",
    ga: "Misa Chat — teachtaire nua-aimseartha",
    it: "Misa Chat — messenger moderno",
    ja: "Misa Chat — モダンなメッセンジャー",
    kn: "Misa Chat — ಆಧುನಿಕ ಮೆಸೆಂಜರ್",
    kk: "Misa Chat — заманауи мессенджер",
    km: "Misa Chat — កម្មវិធីសារទំនើប",
    ko: "Misa Chat — 모던 메신저",
    lo: "Misa Chat — ຜູ້ສົ່ງຂໍ້ຄວາມທັນສະໄໝ",
    lv: "Misa Chat — mūsdienīgs ziņotājs",
    lt: "Misa Chat — šiuolaikiškas messengeris",
    mk: "Misa Chat — модерен гласник",
    ms: "Misa Chat — messenger moden",
    ml: "Misa Chat — ആധുനിക മെസഞ്ചർ",
    mt: "Misa Chat — messagger modern",
    mr: "Misa Chat — आधुनिक मेसेंजर",
    mn: "Misa Chat — орчин үеийн мессенжер",
    ne: "Misa Chat — आधुनिक मेसेन्जर",
    nb: "Misa Chat — moderne messenger",
    fa: "Misa Chat — پیام‌رسان مدرن",
    pl: "Misa Chat — nowoczesny komunikator",
    pt: "Misa Chat — mensageiro moderno",
    pa: "Misa Chat — ਆਧੁਨਿਕ ਮੈਸੇਂਜਰ",
    ro: "Misa Chat — messenger modern",
    sr: "Misa Chat — модеран гласник",
    si: "Misa Chat — නවීන පණිවිඩකරු",
    sk: "Misa Chat — moderný messenger",
    sl: "Misa Chat — sodobni messenger",
    es: "Misa Chat — mensajería moderna",
    sw: "Misa Chat — mjumbe wa kisasa",
    tl: "Misa Chat — modernong messenger",
    tg: "Misa Chat — паёмбари муосир",
    th: "Misa Chat — แชททันสมัย",
    tr: "Misa Chat — modern mesajlaşma",
    uk: "Misa Chat — сучасний месенджер",
    ur: "Misa Chat — جدید پیغام‌رساں",
    uz: "Misa Chat — zamonaviy messenger",
    vi: "Misa Chat — ứng dụng nhắn tin hiện đại",
    cy: "Misa Chat — negesydd modern",
    xh: "Misa Chat — umthunywa wexesha",
    yi: "Misa Chat — מאָדערנער מעסענדזשער",
    yo: "Misa Chat — oluranṣẹ ọ̀hún",
    zu: "Misa Chat — isithunywa sesimanje",
    gu: "Misa Chat — આધુનિક મેસેંજર",
    haw: "Misa Chat — messenger hou",
    ig: "Misa Chat — onyeozi ozi",
};

export const OG_PREVIEW = Object.fromEntries(
    LANGUAGES.map(({ code }) => [code, TAGLINES[code] ?? EN])
);
